### ISSUE TITLE
Improve caching by providing different cache expiration times for different endpoints

### ISSUE THREAD

**Issue by sandeep-ps** [htrc/torchlite-backend#114]
Currently, all endpoints have the same cache expiration time. Specific endpoints can have higher or lower cache expiration times due to the nature of the data (for example, featured datasets are pretty much static). The capability to specify different cache expiration times for different endpoints will be helpful to address this use case. Add a feature to support this use case.

**Comment by gworthey** [comment]
Meant to make caching more sophisticated: currently all endpoints have the same expiration time (set at global level), but it makes more sense to fine-tune endpoint by endpoint.  

@sandeep-ps will implement global expiration to 1 hour (rather than 1 minute currently) as a temporary fix, and this fine-tuned caching will move to post-MVP.

**Comment by sandeep-ps** [comment]
Linked to https://github.com/htrc/torchlite-argocd/issues/7
